config/routes.rb
Rails.application.routes.draw do

  get '/search', to: 'listings#search'

  resources :payments

  resources :listings do
    resources :reservations
  end #7 restful routes auto listed

  get '/my_listings', to: "listings#profile", as: "my_listings"

  get '/my_reservations', to: "reservations#profile", as: "my_reservations"

  get 'home/index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  
   resources :users, only: [:show, :edit, :update, :destroy] 

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  delete "/users/:id/image" => "users#delete_image", as: "remove_image"

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  root 'home#index'

  resources :listings, only: [:index]
  get 'tags/:tag', to: 'listings#index', as: :tag
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :user
  has_many :reservations
  mount_uploaders :avatars, AvatarUploader
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  searchkick match: :word_start, searchable: [:name, :location]
  has_many :available_dates

  def self.tagged_with(name)
  	Tag.find_by_name!(name).listings
  end

  def self.tag_counts
  	Tag.select("tags.*, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
	end

	def tag_list
	  tags.map(&:name).join(", ")
	end

	def tag_list=(names)
	  self.tags = names.split(",").map do |n|
	    Tag.where(name: n.strip).first_or_create!
	  end
	end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy];

  def profile
    @my_listings = current_user.listings
  end

  def search
    @listings = Listing.search(params[:term], fields: ["name", "description","tags"], mispellings: {below: 5})
    if @listings.blank?
      redirect_to listings_path, flash:{danger: "Unforunately, search not found."}
    else
      render :index
    end
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = current_user.listings.new(listing_params)

    if @listing.save
      redirect_to my_listings_path
    else
      render :new
    end
  end

  def index
    if params[:tag]
      @listings = Listing.tagged_with(params[:tag])
    elsif params[:term]
      @listings = Listing.search(params[:term], fields: ["name", "description","tags"], mispellings: {below: 5})
      if @listings.blank?
        flash[:danger] = "Unforunately, search not found."
      end
    else
      @listings = Listing.all
    end
  end


  def show
   
  end

  def update
    @listing.update(listing_params)
    if @listing.save
      redirect_to listings_path
    else
      render :edit
    end
  end

  def edit

  end

  def destroy
    @listing.destroy
    #listings/destroy.html.erb
    redirect_to listings_path #index page that shows
  end

  def set_listing
    @listing = Listing.find(params[:id])
  end

  private
  def listing_params
    params.require(:listing).permit(:name,:description, :price, :property_type, :country, :guests, :beds, :bathrooms, :tag_list, {avatars:[]}, );
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
	def tag_cloud(tags, classes)
	  max = tags.sort_by(&:count).last
	  tags.each do |tag|
	    index = tag.count.to_f / max.count * (classes.size - 1)
	    yield(tag, classes[index.round])
	  end
	end
end

app/views/listings/_form.html.erb
<script>
	$( ".datepicker" ).datepicker({ 
		minDate: +1, 
		maxDate: "+6M", 
		dateFormat: "dd-mm-yy" 
	 });
</script>
<%= form_for @listing do |f| %>
		<table class="listing-form">
			<tr>
				<td class="f-header">Name:</td>
			</tr>
			<tr>
				<td><%= f.text_field :name %></td>
			</tr>
			<tr>
				<td>
					<table style="width:100%">
						<tr>
							<td class="f-header" width="50%">Price per night:</td>
							<td class="f-header">Location</td>
						</tr>
						<tr>
							<td style="padding-right:10px"><%= f.number_field :price %></td>
							<td><%= f.text_field :country %></td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td class="f-header">Description:</td>
			</tr>
			<tr>
				<td><%= f.text_area :description %></td>
			</tr>
			<tr>
				<td>
					<table style="width:100%">
						<tr>
							<td class="f-header">Property Type:</td>
							<td class="f-header">Beds:</td>
							<td class="f-header">Guests:</td>
							<td class="f-header">Bathrooms:</td>
						</tr>
						<tr>
							<td style="padding-right:10px;"><%= f.select(:property_type, ['Apartment', 'Bungalow', 'Hostel'], {}, { :class => 'listing-select' }) %></td>
							<td style="padding-right:10px;"><%= f.select(:beds, [1, 2, 3], {}, { :class => 'listing-select' }) %></td>
							<td style="padding-right:10px;"><%= f.select(:guests, [1, 2, 3], {}, { :class => 'listing-select' }) %></td>
							<td><%= f.select(:bathrooms, [1, 2, 3], {}, { :class => 'listing-select' }) %></td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td class="f-header">Room Images: </td>
			</tr>
			<tr>
				<td><%= f.file_field :avatars, multiple: true %><br/>
					<% @listing.avatars.each do |x| %>
				  	<%= image_tag x.thumb.url %>
				  <% end %>
				</td>
			</tr>
			<tr>
				<td class="f-header">Tags List (separate by commas): </td>
			</tr>
			<tr>
				<td><%= f.text_field :tag_list %>
				</td>
			</tr>
			<tr>
				<td><%= f.submit %></td>
			</tr>
		</table>
<% end %>

app/views/listings/create.html.erb
<h1>Listings#create</h1>
<p>Find me in app/views/listings/create.html.erb</p>

app/views/listings/destroy.html.erb
<h1>Listings#destroy</h1>
<p>Find me in app/views/listings/destroy.html.erb</p>

app/views/listings/edit.html.erb
<div class="container push-down">
	<div class="row">
		<div class="col-sm-3">
			<div class="profile-pic">
				<% if current_user.avatar.url == nil %>
					<%= image_tag "default-avatar.png" %>
				<% else %>
				<%= image_tag current_user.avatar.medium.url %>
				<% end %>
				<br/>
				<strong>Name</strong>: <%= current_user.name %>
				<br/>
			</div>
			<%= render 'users/sidebar' %>
			<br><br/>
			<%= link_to "< Back to My Listings", my_listings_path %>
		</div>
		<div class="col-sm-9">
			<h1>Edit Listings</h1>
			<br/>
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/listings/index.html.erb
<div class="container push-down">
	<div class="row">
		<h1>All Listings</h1>
			<br/>
			<% if @listings %>
				<% @listings.reverse_each do |x| %>
				<div class="listing-box" style="border:1px solid #EBEBEB">
					<div class="row">
						<div class="col-sm-4">
							<div class="listing-avatar">
								 <% if x.avatars == [] %>
												<%= image_tag ("placeholder.jpg") %>
										<% else %>
										 	<%= image_tag (x.avatars[0].medium.url) %>
										<% end %>
							</div>
						</div>
						<div class="col-sm-8">
							<div class="listing-info">
									<table style="width:100%">
										<tr>
											<td width="220" class="f-header">Name :</td>
											<td><%= x.name %></td>
										</tr>
										<tr>
											<td class="f-header">Location :</td>
											<td><%= x.country %></td>
										</tr>
										<tr>
											<td class="f-header">Property Type :</td>
											<td><%= x.property_type %></td>
										</tr>
										<tr>
											<td class="f-header">Listed by:</td>
											<td><%= x.user.name %></td>
										</tr>
										<tr>
											<td class="f-header"></td>
											<td>
												<% if x.user == current_user %>
		   <%= link_to "View Listings", listing_path(x) %> |
				   <%= link_to "Edit Listing", edit_listing_path(x) %> | 
				   <%= link_to "Delete Listing", listing_path(x), method: :delete %>
		  <% else %>
		  <%= link_to "Make Reservation", new_listing_reservation_path(x) %> | <%= link_to "View Listings", listing_path(x) %>
		  <% end %> 
											</td>
										</tr>
									</table>
							</div>
						</div>
					</div>
				</div>
				<br/><br/>
				<% end %>
			<% end %>
	</div>
</div>

app/views/listings/new.html.erb
<div class="container push-down">
	<div class="row">
		<div class="col-sm-3">
			<div class="profile-pic">
				<% if current_user.avatar.url == nil %>
					<%= image_tag "default-avatar.png" %>
				<% else %>
				<%= image_tag current_user.avatar.medium.url %>
				<% end %>
				<br/>
				<strong>Name</strong>: <%= current_user.name %>
				<br/>
			</div>
			<%= render 'users/sidebar' %>
			<br><br/>
			<%= link_to "< Back to My Listings", my_listings_path %>
		</div>
		<div class="col-sm-9">
			<h1>Create Listings</h1>
			<br/>
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/listings/profile.html.erb
<div class="container push-down">
	<div class="row">
		<div class="col-sm-3">
			<div class="profile-pic">
				<% if current_user.avatar.url == nil %>
					<%= image_tag "default-avatar.png" %>
				<% else %>
				<%= image_tag current_user.avatar.medium.url %>
				<% end %>
				<br/>
				<strong>Name</strong>: <%= current_user.name %>
				<br/>
			</div>
			<%= render 'users/sidebar' %>
		</div>
		<div class="col-sm-9">
			<div class="row">
				<h1>My Listings</h1>
			<br/>
			<%= link_to "Create New Listing", new_listing_path, class: "btn-a" %>
					<br/><br/><br/>
					<% if @my_listings %>
						<% @my_listings.reverse_each do |x| %>
						<div class="listing-box" style="border:1px solid #EBEBEB">
							<div class="row">
								<div class="col-sm-5">
									<div class="listing-avatar">
										<% if x.avatars == [] %>
												<%= image_tag ("placeholder.jpg") %>
										<% else %>
										 	<%= image_tag (x.avatars[0].medium.url) %>
										<% end %>
									</div>
								</div>
								<div class="col-sm-7">
									<div class="listing-info">
											<table style="width:100%">
												<tr>
													<td width="180" class="f-header">Name :</td>
													<td><%= x.name %></td>
												</tr>
												<tr>
													<td class="f-header">Location :</td>
													<td><%= x.country %></td>
												</tr>
												<tr>
													<td class="f-header">Property Type :</td>
													<td><%= x.property_type %></td>
												</tr>
								
												<tr>
													<td class="f-header">Listed by:</td>
													<td><%= x.user.name %></td>
												</tr>
												<tr>
													<td class="f-header"></td>
													<td>
														<% if x.user == current_user %>
					<%= link_to "View Listings", listing_path(x) %> |
				   <%= link_to "Edit Listing", edit_listing_path(x) %> | 
				   <%= link_to "Delete Listing", listing_path(x), method: :delete %>
				  <% else %>
				  <%= link_to "Make Reservation", new_listing_reservation_path(x) %> | <%= link_to "View Listings", listing_path(x) %>
				  <% end %> 
													</td>
												</tr>
											</table>
									</div>
								</div>
							</div>
						</div>
						<br/><br/>
						<% end %>
					<% end %>
			</div>		
		</div>
	</div>
</div>

app/views/listings/show.html.erb
    <header id="myCarousel" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators">
        <%for i in 0..@listing.avatars.count - 1 %>
          <li data-target="#myCarousel" data-slide-to="<%=i%>"></li>
          <%end%>
      </ol>

        <!-- Wrapper for Slides -->
        <div class="carousel-inner">
        <% @listing.avatars.each_with_index do |avatar, index|%>
          <div class="item <%= 'active' if index == 0%>">
            <div class="fill" style="background-image:url('<%= avatar.large.url %>');"></div>
          </div>
          <%end%>
      </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>
    </header>

<div class="container push-down" style="padding-bottom:100px;">
	<div class="row">
			<div class="col-sm-3 listing-profile">
				<%  if @listing.user.avatar.url == nil %>
					<%= image_tag "default-avatar.png" %>
				<% else %>
				<%= image_tag @listing.user.avatar.medium.url %>
				<% end %>
				<br/><br/>
				<h2><%= @listing.user.name %></h2>
			</div>
			<div class="col-sm-9 listing-profile-info">
				<h1><%= @listing.name %></h1>
				<p><%= @listing.country %></p>
				<hr>
				<h2>About this listing</h2>
				<table style="width:100%">
						<tr>
							<td width="200" class="f-header">Property Type :</td>
							<td><%= @listing.property_type %></td>
						</tr>	
						<tr>
							<td class="f-header">Price per night:</td>
							<td>RM<%= @listing.price %></td>
						</tr>
						<tr>
							<td class="f-header">No. of guests:</td>
							<td><%= @listing.guests %></td>
						</tr>
						<tr>
							<td class="f-header">No. of beds:</td>
							<td><%= @listing.beds %></td>
						</tr>
						<tr>
							<td class="f-header">No. of bathrooms:</td>
							<td><%= @listing.bathrooms %></td>
						</tr>
						<tr>
							<td class="f-header">Tags:</td>
							<td><%= raw @listing.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></td>
						</tr>
						<tr>
							<td valign="top" width="200" class="f-header">Description :</td>
							<td><%= @listing.description %></td>
						</tr>
						<tr>
													<td class="f-header"></td>
													<td>
														<% if @listing.user == current_user %>
				   <%= link_to "Edit Listing", edit_listing_path(@listing.id) %> | 
				   <%= link_to "Delete Listing", listing_path(@listing.id), method: :delete %>
				  <% else %>
				  <%= link_to "Make Reservation", new_listing_reservation_path(@listing.id) %>
				  <% end %> 
													</td>
												</tr>

					</table>
			</div>
	</div>
</div>

app/views/listings/update.html.erb
<h1>Listings#update</h1>
<p>Find me in app/views/listings/update.html.erb</p>