config/routes.rb
Rails.application.routes.draw do

  get '/search', to: 'listings#search'

  resources :payments

  resources :listings do
    resources :reservations
  end #7 restful routes auto listed

  get '/my_listings', to: "listings#profile", as: "my_listings"

  get '/my_reservations', to: "reservations#profile", as: "my_reservations"

  get 'home/index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  
   resources :users, only: [:show, :edit, :update, :destroy] 

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  delete "/users/:id/image" => "users#delete_image", as: "remove_image"

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  root 'home#index'

  resources :listings, only: [:index]
  get 'tags/:tag', to: 'listings#index', as: :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  validates :email, uniqueness: true, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: "format not valid"}
  #validates :password, presence: true, format: { with: /.{5}/, message: "minimum length of 5"}
  has_many :listings
  has_many :reservations

  mount_uploader :avatar, ProfilePictureUploader

  has_many :authentications, :dependent => :destroy

  def self.create_with_auth_and_hash(authentication,auth_hash)
    create! do |u|
      u.name = auth_hash["info"]["name"]
      u.email = auth_hash["extra"]["raw_info"]["email"]
      u.authentications<<(authentication)
    end
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

  def password_optional?
    true
  end
end

app/controllers/clearance/users_controller.rb
class Clearance::UsersController < Clearance::BaseController
  if respond_to?(:before_action)
    before_action :redirect_signed_in_users, only: [:create, :new]
    skip_before_action :require_login, only: [:create, :new], raise: false
    skip_before_action :authorize, only: [:create, :new], raise: false
  else
    before_filter :redirect_signed_in_users, only: [:create, :new]
    skip_before_filter :require_login, only: [:create, :new], raise: false
    skip_before_filter :authorize, only: [:create, :new], raise: false
  end

  def new
    @user = user_from_params
    render template: "users/new"
  end

  def create
    @user = user_from_params

    if @user.save
      # Tell the UserMailer to send a welcome email after save
      UserMailer.welcome_email(@user).deliver_now
      sign_in @user
      redirect_back_or url_after_create
    else
      render template: "users/new"
    end
  end

  private

  def avoid_sign_in
    warn "[DEPRECATION] Clearance's `avoid_sign_in` before_filter is " +
      "deprecated. Use `redirect_signed_in_users` instead. " +
      "Be sure to update any instances of `skip_before_filter :avoid_sign_in`" +
      " or `skip_before_action :avoid_sign_in` as well"
    redirect_signed_in_users
  end

  def redirect_signed_in_users
    if signed_in?
      #redirect_to Clearance.configuration.redirect_url
      redirect_to home_index_path
    end
  end

  def url_after_create
    Clearance.configuration.redirect_url
  end

  def user_from_params
  	name = user_params.delete(:name)
    email = user_params.delete(:email)
    password = user_params.delete(:password)

    Clearance.configuration.user_model.new(user_params).tap do |user|
    	user.name = name
      user.email = email
      user.password = password
    end
  end

  def user_params
    params[Clearance.configuration.user_parameter] || Hash.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_listing, only: [:show, :edit, :update,:delete_image]

  def show 
    
  end

	def edit

	end

	def update
    @user.update(user_params)
    if @user.save
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def delete_image
  	@user.remove_avatar!
  	@user.save
  	redirect_to user_path(current_user)
  end


	def set_listing
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name,:email,:avatar)
  end

end

app/views/users/_form.html.erb
 	<%= f.label :email %>
  <%= f.text_field :email, type: 'email' %>
  <br/>
  <%= f.file_field :avatar %>
	<%= image_tag @user.avatar.thumb.url %>

	

app/views/users/_sidebar.html.erb
<h2>Dashboard</h2>
<ul class="sidebar">
	<li <% if current_page?(edit_user_path(current_user)) || current_page?(user_path(current_user)) %> class="active" <% end %>><%= link_to "Profile", user_path(current_user) %></li>

	<li <% if current_page?(my_listings_path) || current_page?(new_listing_path) %> class="active" <% end %>><%= link_to "My listing", my_listings_path %></li>

	<li <% if current_page?(my_reservations_path)%> class="active" <% end %>><%= link_to "My Reservations", my_reservations_path %></li>
</ul>

app/views/users/edit.html.erb
<div class="container push-down">
	<div class="row">
		<h1>Edit your profile</h1>
		<br/>
		<%= form_for @user do |f| %>
		<div class="col-sm-3">
			<div class="profile-pic">
				<% if @user.avatar.url == nil %>
					<%= image_tag "default-avatar.png" %>
					<br/>
					<%= f.file_field :avatar %>
				<% else %>
				<%= image_tag @user.avatar.medium.url %>
				<br/>
				<%= f.file_field :avatar %>
				<br/>
				<%= link_to "Remove the image",remove_image_path(current_user), method: :delete %>
				<% end %>

			</div>
			<%= render 'sidebar' %>
		</div>
		<div class="col-sm-9">
			<div class="profile-info">
				<table>
					<tr>
						<td width="30%" class="bold">Name</td>
						<td><%= f.text_field :name, type: 'text' %></td>
					</tr>
					<tr>
						<td class="bold">Email</td>
						<td><%= f.text_field :email, type: 'email' %></td>
					</tr>
					<tr>
						<td colspan="2">
							<div class="submit-field">
					      <%= f.submit %>
					    </div>
						</td>
					</tr>
				</table>
			</div>
		</div>
		<% end %>
	</div>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |f| %>
      <%= render :partial => "users/form", :locals=>{:f=>f} %>

    <div class="submit-field">
      <%= f.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container push-down">
	<div class="row">
		<div class="col-sm-3">
			<div class="profile-pic">
				<% if @user.avatar.url == nil %>
					<%= image_tag "default-avatar.png" %>
				<% else %>
				<%= image_tag @user.avatar.medium.url %>
				<% end %>

			</div>
			<%= render 'sidebar' %>
		</div>
		<div class="col-sm-9">
			<div class="profile-info">
				<table>
					<tr>
						<td width="30%" class="bold">Name</td>
						<td><%= @user.name %></td>
					</tr>
					<tr>
						<td class="bold">Email</td>
						<td><%= @user.email %></td>
					</tr>
					<tr>
						<td colspan="2">
							<%= link_to "Edit Profile", edit_user_path %>
						</td>
					</tr>
				</table>
			</div>
		</div>
	</div>
</div>