config/routes.rb
Rails.application.routes.draw do

  get '/search', to: 'listings#search'

  resources :payments

  resources :listings do
    resources :reservations
  end #7 restful routes auto listed

  get '/my_listings', to: "listings#profile", as: "my_listings"

  get '/my_reservations', to: "reservations#profile", as: "my_reservations"

  get 'home/index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  
   resources :users, only: [:show, :edit, :update, :destroy] 

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  delete "/users/:id/image" => "users#delete_image", as: "remove_image"

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  root 'home#index'

  resources :listings, only: [:index]
  get 'tags/:tag', to: 'listings#index', as: :tag
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	 belongs_to :user
	 belongs_to :listing
	 has_many :payments
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :require_login, only: [:new, :create]
  before_action :set_listing, only: [:show, :edit, :update, :destroy]


  def new
    @listing = Listing.find(params[:listing_id])
    @reservation = Reservation.new
    @unavailable_dates = AvailableDate.where(listing_id: params[:listing_id])
    @unavailable_dates = @unavailable_dates.pluck(:unavailable_date).map{ |a| a.strftime('%d-%m-%Y') }
  end

  def create
    @listing = Listing.find(reservation_params[:listing_id])
    start_date = Date.parse(reservation_params[:check_in])
    end_date = Date.parse(reservation_params[:check_out])
    total_days = end_date.mjd - start_date.mjd
    @reservation = current_user.reservations.new(check_in: reservation_params[:check_in], check_out: reservation_params[:check_out], total_sum: reservation_params[:total_sum].to_i * total_days, listing_id: reservation_params[:listing_id])



    if @reservation.save
      total_days.times do

        @listing.available_dates << AvailableDate.create(unavailable_date: start_date)
          start_date += 1
      end
      redirect_to my_reservations_path
    else
      render :new
    end
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end

  def profile
    @my_reservations = current_user.reservations
  end


  private
  def set_listing
    @reservation = Reservation.find(params[:id])
  end


  def reservation_params
    params.require(:reservation).permit(:check_in, :check_out, :total_sum, :listing_id);
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
	<script>
		var unavailable_dates = <%= @unavailable_dates.inspect.html_safe %>

		 $( ".r_datepicker" ).datepicker({ 
	   	minDate: +1, 
	   	maxDate: "+6M", 
	   	dateFormat: "dd-mm-yy",
	   	beforeShowDay: DisableSpecificDates
	   });

	   function DisableSpecificDates(date) {
   var string = jQuery.datepicker.formatDate('dd-mm-yy', date);
   return [unavailable_dates.indexOf(string) == -1];
 };
	</script>

 	<%= f.label :check_in %>
  <%= f.text_field :check_in, class: "r_datepicker" %> 
  <%= f.label :check_out %>
  <%= f.text_field :check_out, class: "r_datepicker" %>
  <br/>

app/views/reservations/create.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

app/views/reservations/destroy.html.erb
<h1>Reservations#destroy</h1>
<p>Find me in app/views/reservations/destroy.html.erb</p>

app/views/reservations/edit.html.erb
<h1>Reservations#edit</h1>
<p>Find me in app/views/reservations/edit.html.erb</p>

app/views/reservations/index.html.erb
<h1>Reservations#index</h1>
<p>Find me in app/views/reservations/index.html.erb</p>

app/views/reservations/new.html.erb
<%= content_for(:body_attributes) do %>data-no-turbolink<% end %>

    <header id="myCarousel" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators">
        <%for i in 0..@listing.avatars.count - 1 %>
          <li data-target="#myCarousel" data-slide-to="<%=i%>"></li>
          <%end%>
      </ol>

        <!-- Wrapper for Slides -->
        <div class="carousel-inner">
        <% @listing.avatars.each_with_index do |avatar, index|%>
          <div class="item <%= 'active' if index == 0%>">
            <div class="fill" style="background-image:url('<%= avatar.large.url %>');"></div>
          </div>
          <%end%>
      </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>

    </header>

<div class="container push-down" style="padding-bottom:100px;">
	<div class="row">
			<div class="col-sm-3 listing-profile">
				<%  if @listing.user.avatar.url == nil %>
					<%= image_tag "default-avatar.png" %>
				<% else %>
				<%= image_tag @listing.user.avatar.medium.url %>
				<% end %>
				<br/><br/>
				<h2><%= @listing.user.name %></h2>
			</div>
			<div class="col-sm-9 listing-profile-info">
				<h1><%= @listing.name %></h1>
				<p><%= @listing.country %></p>
				<hr>
				<h2>About this listing</h2>
				<table style="width:100%">
						<tr>
							<td width="200" class="f-header">Property Type :</td>
							<td><%= @listing.property_type %></td>
						</tr>	
						<tr>
							<td class="f-header">Price per night:</td>
							<td>RM<%= @listing.price %></td>
						</tr>
						<tr>
							<td class="f-header">No. of guests:</td>
							<td><%= @listing.guests %></td>
						</tr>
						<tr>
							<td class="f-header">No. of beds:</td>
							<td><%= @listing.beds %></td>
						</tr>
						<tr>
							<td class="f-header">No. of bathrooms:</td>
							<td><%= @listing.bathrooms %></td>
						</tr>
						<tr>
							<td class="f-header">Tags:</td>
							<td><%= raw @listing.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></td>
						</tr>
						<tr>
							<td valign="top" width="200" class="f-header">Description :</td>
							<td><%= @listing.description %></td>
						</tr>
						<tr>
							<td valign="top" width="200" class="f-header">Make Reservations</td>
							<td>
								<%= form_for [@listing, @reservation] do |f| %>
									<%= render :partial => "form", :locals=>{:f=>f} %>
									 <%= f.hidden_field :listing_id, value: @listing.id %>
						   			<%= f.hidden_field :total_sum, value: @listing.price %>
						   			<br/>
								 <div class="submit-field">
						      <%= f.submit %>
						    </div>
    					<% end %>
							</td>
						</tr>

					</table>
			</div>
	</div>
</div>

app/views/reservations/profile.html.erb
<div class="container push-down">
	<div class="row">
		<div class="col-sm-3">
			<div class="profile-pic">
				<% if current_user.avatar.url == nil %>
					<%= image_tag "default-avatar.png" %>
				<% else %>
				<%= image_tag current_user.avatar.medium.url %>
				<% end %>
				<br/>
				<strong>Name</strong>: <%= current_user.name %>
				<br/>
			</div>
			<%= render 'users/sidebar' %>
			<br><br/>
			<%= link_to "< Back to My Listings", my_listings_path %>
		</div>
		<div class="col-sm-9">
			<h1>My Reservations</h1>
			<br/>
			<% @my_reservations.each do |x| %>
			<div class="listing-box" style="border:1px solid #EBEBEB">
				<div class="row">
					<div class="col-sm-5">
						<div class="listing-avatar">
							<% if x.listing.avatars == [] %>
									<%= image_tag ("placeholder.jpg") %>
							<% else %>
							 	<%= image_tag (x.listing.avatars[0].medium.url) %>
							<% end %>
						</div>
					</div>

					<div class="col-sm-7">
						<div class="listing-info">
								<table style="width:100%">
									<tr>
										<td width="180" class="f-header">Name :</td>
										<td><%= x.listing.name %></td>
									</tr>
									<tr>
										<td class="f-header">Location :</td>
										<td><%= x.listing.country %></td>
									</tr>
									<tr>
										<td class="f-header">Property Type :</td>
										<td><%= x.listing.property_type %></td>
									</tr>
									<tr>
										<td class="f-header">Listed by:</td>
										<td><%= x.listing.user.name %></td>
									</tr>
									<tr>
										<td class="f-header">Check in:</td>
										<td><%= x.check_in %></td>
									</tr>
									<tr>
										<td class="f-header">Check out:</td>
										<td><%= x.check_out %></td>
									</tr>
									<tr>
										<td class="f-header">Payment Status:</td>
										<td><% if x.payments.where(status: :authorized).count == 0%>
								      <span class="btn btn-danger"> NOT PAID </span>
								       <%= link_to 'Pay Now' , new_payment_path + "?id=" + x.id.to_s, class: "btn btn-warning"  %>
								      <% else %>
								      <span class="btn btn-success">PAID</span>
								      <% end %>
								    </td>
									</tr>
								</table>
							</div>
					</div>
				</div>	
			</div>
			<br/>
			<% end %>
		</div>
	</div>
</div>

app/views/reservations/show.html.erb
<h1>Reservations#show</h1>
<p>Find me in app/views/reservations/show.html.erb</p>

app/views/reservations/update.html.erb
<h1>Reservations#update</h1>
<p>Find me in app/views/reservations/update.html.erb</p>