config/routes.rb
Rails.application.routes.draw do

  get '/search', to: 'listings#search'

  resources :payments

  resources :listings do
    resources :reservations
  end #7 restful routes auto listed

  get '/my_listings', to: "listings#profile", as: "my_listings"

  get '/my_reservations', to: "reservations#profile", as: "my_reservations"

  get 'home/index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  
   resources :users, only: [:show, :edit, :update, :destroy] 

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  delete "/users/:id/image" => "users#delete_image", as: "remove_image"

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  root 'home#index'

  resources :listings, only: [:index]
  get 'tags/:tag', to: 'listings#index', as: :tag
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


  <script src="https://js.braintreegateway.com/v2/braintree.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/flexslider/2.6.3/jquery.flexslider-min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
  <%= csrf_meta_tag %>
</head>

<body <%= yield(:body_attributes) %>>

  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><%= image_tag "pairbnb.png"%></a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li>
            <form class="navbar-form" role="search" method="get" action="/listings">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search" name="term">
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                    </div>
                </div>
            </form>
            
          </li>
        </ul>
  <ul class="nav navbar-nav navbar-right">

   <% if current_user %>
    <li <% if current_page?(new_listing_path) %> class="active"  <% end %>><%= link_to "Become a host", new_listing_path %></li>
    <li <% if current_page?(listings_path) %> class="active"  <% end %>><%= link_to "Listings", listings_path %></li>
    <li class="logged_in dropdown">
       <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
      <% if current_user.name == nil %>
        WELCOME, <%= current_user.email %>
      <% else %>
         WELCOME, <%= current_user.name %>
      <% end %></a>
      <ul class="dropdown-menu">
        <li><%= link_to "Dashboard", user_path(current_user) %></li>
        <li class="btn-logout"><%= button_to "Log out", sign_out_path, method: :delete %></li>        
      </ul>
   </li>
    <% else %> 
    <li><button type="button" class="btns btn_signup" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-user"></span> Sign Up</button></li>
    <li><button type="button" class="btns btn_login" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-log-in"></span> Login</button></li>
    <% end %>
  </ul>
      </div>
    </div>
  </nav>

  <!-- Content !-->
  <%= yield %>
  <div id="flash" class="container">
      <% if flash %>
        <% flash.each do |key, value| %>
          <%= value %>
          <br/><br/>
          <%= link_to "Back to Home", root_path %>
        <% end %>
      <% end %>
  </div>
  <!-- End Content !-->

  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Pairbnb</h4>
        </div>
        <div class="modal-body">
          
            <div class="fb-button">
              <a href="/auth/facebook" id="sign_in"><i class="fa fa-facebook" aria-hidden="true"></i><span style="padding-left:20px;"></span>Sign in with Facebook</a>
            </div>
            <div class="or">
              or
            </div>
            <!-- SIGN UP FEATURE !-->
            <div id="login">
              <h2>Sign in with Email</h2>
              <%= form_for :session, url: session_path, :html => {:id => "flogin"} do |form| %>
              <table>
                <tr>
                  <td><%= form.text_field :email, type: 'email', placeholder: "Email" %></td>
                </tr>
                <tr>
                    <td><%= form.password_field :password, placeholder: "Password" %></td>
                </tr>
                <tr>
                    <td><%= form.submit %></td>
                </tr>
                <tr>
                  <td style="text-align:right"><%= link_to t(".forgot_password"), new_password_path %></td>
                </tr>
                <tr>
                      <td style="padding-top:10px;"><p id="errors-login"></p></td>
                    </tr>
                <tr>
                  <td>
                    Don't have a Pairbnb account? <span id="btn-fake" class="btn_signup">Sign up</span>
                  </td>
                </tr> 

              </table>
              <% end %>
            </div>


            <div id="signup">
              <div id="clearance" class="sign-up">
                <h2>Sign up with Email</h2>
                <%= form_for User.new do |form| %>
                <table>
                  <tr>
                    <td><%= form.text_field :name, placeholder: "Name" %></td>
                  </tr>
                  <tr>
                    <td><%= form.text_field :email, placeholder: "Email" %></td>
                  </tr>
                  <tr>
                    <td><%= form.password_field :password, placeholder: "Password" %></td>
                  </tr> 
                  <tr>
                    <td><%= form.submit %></td>
                  </tr>
                  <tr>
                    <td>Already have a Pairbnb account? <span id="btn-fake" class="btn_login">Login</span></td>
                  </tr>
                </table>
                <% end %>
              </div>
            </div>
            <!-- END SIGN UP FEATURE !-->
        </div>
        <div class="modal-footer">
          <button type="button" class="btns btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </body>
</html>